### ISSUE TITLE
Error pushing DAR to XLD server

### ISSUE THREAD

**Issue by brhahlen** [xebialabs-community/xld-xldeploy-plugin#2]
When trying to deploying a deployable with the DarPackage defined, the following error pops up:

```
Error while evaluating rule [ext.deployit.plugin.xldeploy.ExportToXLDeployServerContributor.exportDarAndPushToServer]: 
org/apache/http/entity/mime/content/ContentBody
```

**Comment by rchrd** [comment]
@brhahlen Did you add the httpmime-`<version>`.jar to the classpath?

**Comment by brhahlen** [comment]
@rchrd Yes, I found it in the docs, eventually, but forgot to close this.
Closed now.
